# This file describes the GitHub Actions workflow for continuous integration of XS Core.
name: EMU Test

on:
  push:
    branches: [ master, ptw-pre-nl ]
  pull_request:
    branches: [ master ]

jobs:
  emu-performance:
    runs-on: self-hosted
    continue-on-error: false
    name: EMU - Performance
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: set env
        run: |
          echo "NEMU_HOME=/home/ci-runner/xsenv/NEMU" >> $GITHUB_ENV
          echo "AM_HOME=/home/ci-runner/xsenv/nexus-am" >> $GITHUB_ENV
          echo "PERF_HOME=/bigdata/xs-perf/${GITHUB_SHA}" >> $GITHUB_ENV
          mkdir -p /bigdata/xs-perf/${GITHUB_SHA}
      - name: Build EMU
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build \
            --dramsim3 /home/ci-runner/xsenv/DRAMsim3            \
            --disable-log --with-dramsim3 --threads 16 --trace
          cp $GITHUB_WORKSPACE/build/emu /home/ci-runner/actions-runner/emu/emu-${GITHUB_SHA}
          cp $GITHUB_WORKSPACE/build/SimTop.v /home/ci-runner/actions-runner/emu/SimTop-${GITHUB_SHA}.v
      - name: SPEC06 Test - mcf
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci mcf 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/mcf.log
      - name: SPEC06 Test - xalancbmk
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci xalancbmk 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/xalancbmk.log
      - name: SPEC06 Test - gcc
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci gcc 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/gcc.log
      - name: SPEC06 Test - namd
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci namd 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/namd.log
      - name: SPEC06 Test - milc
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci milc 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/milc.log
      - name: SPEC06 Test - lbm
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci lbm 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/lbm.log
      - name: SPEC06 Test - gromacs
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --threads 16 --max-instr 5000000 --numa --ci gromacs 2> perf.log
          cat perf.log | sort | tee $PERF_HOME/gromacs.log
